beacon:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Relative to dbt/ 
      path: ../data/warehouse/beacon.duckdb
      external_root: ../data/gold
      extensions:
        - delta
      settings:
        TimeZone: UTC  
      threads: 4